name: Code Review by Aide

on:
  pull_request:
    types: [opened, reopened]

jobs:
  ReviewPullRequest:
    runs-on: [self-hosted]
    steps:
      - name: Setup Node.Js Enviornment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"
        continue-on-error: false

      - name: Reviewing Pull Request
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node C:\\sabio_modules\\sabia\\bin\\index.js code-review  opts='{run:true}' number="${{github.event.pull_request.number}}" repo="${{github.repository}}" login="${{ github.event.pull_request.user.login }}"
