name: Send Pull Request Data

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  SendData:
    runs-on: [self-hosted]
    steps:
      - name: Setup Node.Js Enviornment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"
        continue-on-error: false

      - name: Sending PR Data
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node C:\\sabio_modules\\sabia\\bin\\index.js send-pr-data number="${{github.event.pull_request.number}}" repo="${{github.repository}}"
